### ISSUE TITLE
Error parsing Bootstrap 3.3.4 CSS

### ISSUE THREAD

**Issue by hrj** [radkovo/jStyleParser#26]
Hi,
I was testing a website which uses Bootstrap CSS 3.3.4 minified version, and I got the following exception:
```
Caused by: org.antlr.runtime.tree.RewriteEmptyStreamException: rule terms
	at org.antlr.runtime.tree.RewriteRuleElementStream._next(RewriteRuleElementStream.java:158)
	at org.antlr.runtime.tree.RewriteRuleElementStream.nextTree(RewriteRuleElementStream.java:145)
	at cz.vutbr.web.csskit.antlr.CSSParser.media_expression(CSSParser.java:2991)
	at cz.vutbr.web.csskit.antlr.CSSParser.media_term(CSSParser.java:2763)
	at cz.vutbr.web.csskit.antlr.CSSParser.media_query(CSSParser.java:2628)
	at cz.vutbr.web.csskit.antlr.CSSParser.media(CSSParser.java:2473)
	at cz.vutbr.web.csskit.antlr.CSSParser.atstatement(CSSParser.java:1430)
	at cz.vutbr.web.csskit.antlr.CSSParser.statement(CSSParser.java:908)
	at cz.vutbr.web.csskit.antlr.CSSParser.stylesheet(CSSParser.java:786)
	at cz.vutbr.web.csskit.antlr.CSSParserFactory$SourceType$2.getAST(CSSParserFactory.java:78)
	at cz.vutbr.web.csskit.antlr.CSSParserFactory$SourceType.encapsulateException(CSSParserFactory.java:191)
	at cz.vutbr.web.csskit.antlr.CSSParserFactory$SourceType.access$100(CSSParserFactory.java:39)
	at cz.vutbr.web.csskit.antlr.CSSParserFactory$SourceType$2.getAST(CSSParserFactory.java:84)
	at cz.vutbr.web.csskit.antlr.CSSParserFactory.feedParser(CSSParserFactory.java:387)
	at cz.vutbr.web.csskit.antlr.CSSParserFactory.createTreeParser(CSSParserFactory.java:354)
	at cz.vutbr.web.csskit.antlr.CSSParserFactory.parseAndImport(CSSParserFactory.java:322)
	at cz.vutbr.web.csskit.antlr.CSSParserFactory.parse(CSSParserFactory.java:226)
	at cz.vutbr.web.csskit.antlr.CSSParserFactory.parse(CSSParserFactory.java:253)

```

I hope the stack trace is sufficient to help you find the problem. Let me know if you need more info.

**Comment by hrj** [comment]
This exception can be reproduced with this CSS:
```
@media (transform-3d) {
}
```

The grammar for media queries is specified [here](http://www.w3.org/TR/2012/REC-css3-mediaqueries-20120619/#syntax). Apparently, they allow any identifier for the media-type and media-feature.

**Comment by radkovo** [comment]
Thanks for locating the key rule, this helped a lot!
