### ISSUE TITLE
NullPointerException on 'has' css selector

### ISSUE THREAD

**Issue by nicoloboschi** [radkovo/jStyleParser#81]
Processing this code:
 ` <html><head><style type='text/css'>td:has(.servNoPad) { padding:0px !important; }</style><body></body></html>
`

I get this NPE:
`
java.lang.NullPointerException
	at cz.vutbr.web.csskit.antlr4.CSSParserVisitorImpl.visitSelpart(CSSParserVisitorImpl.java:1254)
	at cz.vutbr.web.csskit.antlr4.CSSParserVisitorImpl.visitSelector(CSSParserVisitorImpl.java:1217)
	at cz.vutbr.web.csskit.antlr4.CSSParserVisitorImpl.visitCombined_selector(CSSParserVisitorImpl.java:1139)
	at cz.vutbr.web.csskit.antlr4.CSSParserVisitorImpl.visitRuleset(CSSParserVisitorImpl.java:662)
	at cz.vutbr.web.csskit.antlr4.CSSParserVisitorImpl.visitStatement(CSSParserVisitorImpl.java:282)
	at cz.vutbr.web.csskit.antlr4.CSSParserVisitorImpl.visitStylesheet(CSSParserVisitorImpl.java:241)
	at cz.vutbr.web.csskit.antlr4.CSSParserFactory.parse(CSSParserFactory.java:206)
	at cz.vutbr.web.csskit.antlr4.CSSParserFactory.parseAndImport(CSSParserFactory.java:147)
	at cz.vutbr.web.csskit.antlr4.CSSParserFactory.parse(CSSParserFactory.java:72)
	at cz.vutbr.web.csskit.antlr4.CSSParserFactory.parse(CSSParserFactory.java:93)
	at cz.vutbr.web.css.CSSFactory.parse(CSSFactory.java:500)
`

**Comment by eolivelli** [comment]
This is a reproducer with 3.1

`CSSFactory.parse("td:has(.servNoPad) { padding:0px !important; }");`

this is the stacktrace of the error
```
java.lang.NullPointerException
	at cz.vutbr.web.csskit.antlr4.CSSParserVisitorImpl.visitSelpart(CSSParserVisitorImpl.java:1254)
	at cz.vutbr.web.csskit.antlr4.CSSParserVisitorImpl.visitSelector(CSSParserVisitorImpl.java:1217)
	at cz.vutbr.web.csskit.antlr4.CSSParserVisitorImpl.visitCombined_selector(CSSParserVisitorImpl.java:1139)
	at cz.vutbr.web.csskit.antlr4.CSSParserVisitorImpl.visitRuleset(CSSParserVisitorImpl.java:662)
	at cz.vutbr.web.csskit.antlr4.CSSParserVisitorImpl.visitStatement(CSSParserVisitorImpl.java:282)
	at cz.vutbr.web.csskit.antlr4.CSSParserVisitorImpl.visitStylesheet(CSSParserVisitorImpl.java:241)
	at cz.vutbr.web.csskit.antlr4.CSSParserFactory.parse(CSSParserFactory.java:206)
	at cz.vutbr.web.csskit.antlr4.CSSParserFactory.parseAndImport(CSSParserFactory.java:147)
	at cz.vutbr.web.csskit.antlr4.CSSParserFactory.parse(CSSParserFactory.java:72)
	at cz.vutbr.web.csskit.antlr4.CSSParserFactory.parse(CSSParserFactory.java:93)
	at cz.vutbr.web.css.CSSFactory.parse(CSSFactory.java:500)
```

I will be happy to provide a patch, can someone give me some pointer ?

**Comment by eolivelli** [comment]
Created patch #82
